on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup variables
      id: vars
      run: |
        echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

    - name: Push
      run: dotnet nuget push ReactRio.Utils.${{ env.VERSION }}.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.NUGET_KEY }}